---
version: '3.7'
services:
  gitlab-ci-runner:
    image: melioconsulting/gitlab-runner:latest
    container_name: gitlab-ci-runner
    # env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD:$PWD
      - ./config.toml:/etc/gitlab-runner/config.toml
    working_dir: $PWD
    privileged: true
